version: 3
tasks:
  run:
    cmd: go run .
  build:
    cmd: go build .
  lint:
    cmd: golangci-lint run
  bundle:
    cmds:
      - mkdir -p sporthalle.app/Contents/MacOS
      - mkdir -p sporthalle.app/Contents/Resources
      - cp Info.plist sporthalle.app/Contents/.
      - go build -o sporthalle.app/Contents/MacOS/sporthalle
      - cp app.icns sporthalle.app/Contents/Resources/sporthalle.icns
      - mv sporthalle.app /Applications/sporthalle.app
      #- task: launch
  launch:
    cmd: open sporthalle.app
  remove:
    cmd: trash /Applications/sporthalle.app