version: 3
tasks:
  build-all:
    cmds:
      - task: build
      - task: build-tray
      - task: build-fn
  default:
    cmd: task --list-all
    desc: "list all available tasks"
  build-tray:
    cmd: cd sporthalle-tray && go build .
    desc: "build the macOs tray app"
  build-fn:
    cmd: cd sporthalle-fn && go build .
    desc: "build the function app"
  runfn:
    cmd: go run sporthalle-fn/fn.go
    desc: "run the function app"
  runtray:
    cmd: go run sporthalle-tray/tray.go
    desc: "run the macOs tray app"
  test-lib:
    cmd: go test -v ./...
  test-fn:
    cmd: cd sporthalle-fn && go test -v ./...
  build:
    cmd: cd lib && go build ./...
    desc: "build the core library"
  lint:
    cmd: golangci-lint run
    desc: "run golangci-lint"
  bundle:
    cmds:
      - mkdir -p sporthalle.app/Contents/MacOS
      - mkdir -p sporthalle.app/Contents/Resources
      - cp Info.plist sporthalle.app/Contents/.
      - go build -o sporthalle.app/Contents/MacOS/sporthalle/cmd/tray
      - cp app.icns sporthalle.app/Contents/Resources/sporthalle.icns
      - mv sporthalle.app /Applications/sporthalle.app
      #- task: launch
  launch:
    cmd: open sporthalle.app
  remove:
    cmd: trash /Applications/sporthalle.app