version: 3
tasks:
  run:
    cmd: go run .
  build:
    cmd: go build .
  lint:
    cmd: golangci-lint run
  dockerize:
    cmd: docker build . -t sporthalle:{{.VERSION}}
    vars:
      VERSION: 1.0.0
  bundle:
    cmds:
      - mkdir -p sporthalle.app/Contents/MacOS
      - go build -o sporthalle.app/Contents/MacOS/sporthalle
      - task: launch
  launch:
    cmd: open sporthalle.app
